using NUnit.Framework;
using System.Collections;
using UnityEngine;

/// <summary>
/// ЕЙПЌКЏРЬ 4 ШЙЕцНУ ЦЏМіАјАнПЁ ЛчПыЕЧДТ ПЁГЪСі БИУМ
/// </summary>
public class EnergyCircle : MonoBehaviour
{
    [Header("----- УЪБт ММЦУ АЊ -----")]
    [SerializeField] float _initialRadius = 1f;     // УЪБт ЙнАц
    [SerializeField] float _maxRadius = 2f;         // ЧЎ ТїСіНУ ЙнАц
    [SerializeField] float _bonusRadius = 2f;       // ЧЎ ТїСіНУ КИГЪНКЗЮ СІАјЕЧДТ ЙнАц
    [SerializeField] float _initialDamage = 5f;     // УЪБт ЕЅЙЬСі
    [SerializeField] float _maxDamage = 20f;        // ЧЎ ТїСіНУ ЕЅЙЬСі
    [SerializeField] float _bonusDamage = 20f;      // ЧЎ ТїСіНУ КИГЪНКЗЮ СІАјЕЧДТ ЕЅЙЬСі
    [SerializeField] float _moveSpeed = 5f;         // БИУМ РЬЕП МгЕЕ
    [SerializeField] float _lifetime = 10f;          // ЙпЛч ШФ Л§СИ НУАЃ

    [Header("----- ЙпЛчНУ ЙоОЦПУ АЊ -----")]
    [SerializeField] float _expansionDuration;      // УжМв 0УЪКЮХЭ 1.5УЪБюСі ЙоОЦПШ
    [SerializeField] Vector3 _moveDir;

    [Header("----- ЗБХИРг ЕЅРЬХЭ -----")]
    [SerializeField] float _currentRadius;
    [SerializeField] float _currentDamage;
    [SerializeField] float _timer;

    public void Initialize(float expansionDuration, Vector3 moveDir)
    {
        _expansionDuration = expansionDuration;
        _moveDir = moveDir;
        SetEnergyCircle(_expansionDuration);
        _timer = 0f;
    }

    private void Update()
    {
        Move(_moveDir);
        // ШЄНУЖѓЕЕ КЎПЁ КЮЕњШїСі ОЪАэ РЯСЄ НУАЃ СіГЊИщ РкЕП МвИъ
        _timer += Time.deltaTime;
        if(_timer >= _lifetime)
        {
            GameManager.Instance.PoolManager.ReleaseToPool(gameObject);
        }
    }

    void SetEnergyCircle(float expansionDuration)
    {
        // 0УЪРЯЖЉ УЪБтАЊ, 1.5УЪРЯЖЉ УжДыАЊИИХ­ localScaleАњ ЕЅЙЬСі МГСЄ
        float ratio = Mathf.Clamp01(expansionDuration / 1.5f);
        _currentRadius = Mathf.Lerp(_initialRadius, _maxRadius, ratio);
        _currentDamage = Mathf.Lerp(_initialDamage, _maxDamage, ratio);

        // ИИОр УжДыФЁПЁ ЕЕДоЧпДйИщ КИГЪНК УпАЁ
        if (expansionDuration >= 1.5f)
        {
            _currentRadius += _bonusRadius;
            _currentDamage += _bonusDamage;
        }
        Vector3 currentScale = Vector3.one * 0.5f;
        transform.localScale = currentScale * _currentRadius;
    }

    void Move(Vector3 moveDir)
    {
        transform.position += moveDir * _moveSpeed * Time.deltaTime;
    }

    private void OnTriggerEnter(Collider other)
    {
        if (other.CompareTag(Constants.TAG_MONSTER))
        {
            GameManager.Instance.PlayerStatManager.TakeDamage(WeaponType.Rifle, ATTACKTYPE.SPECIALATTACK, other.transform);
            GameManager.Instance.PoolManager.ReleaseToPool(gameObject);
        }
        if(other.CompareTag(Constants.TAG_WALL))
        {
            GameManager.Instance.PoolManager.ReleaseToPool(gameObject);
        }
    }
}