using System;
using UnityEngine;


[RequireComponent(typeof(SkillChoose))]
public class TechItem : MonoBehaviour
{ 
    public void OnTriggerEnter(Collider other)
    {
        GetSkill();
    }

  
    #region НКХГ НРЕц

    private TechSelectPackType _TechCompany;
    /// <summary>
    /// НКХГ НРЕц
    /// </summary>
    public void GetSkill()
    {
        SkillChoose skillchoose = GetComponent<SkillChoose>();
        _TechCompany = TechSelectPackType.Company4;
        // ШИЛч СіСЄ
        skillchoose.SetSkillCompany(_TechCompany);
        skillchoose.SetBtn();
    }
    #endregion

    #region НКХГ ОїБзЗЙРЬЕх
   

    public void SkillUpgrade()
    {
        SkillChoose skillchoose = gameObject.GetComponent<SkillChoose>();
        skillchoose.SetUpgradeBtn();
    }
    #endregion
}
