using System;
using System.Collections.Generic;
using UnityEngine;

public class Hero : MonoBehaviour
{
    [Header("HeroВЈ")]
    [SerializeField] HeroModel _model;
    [SerializeField] Mover _mover;
    [SerializeField] HeroAnimator _animator;
    [SerializeField] InteractableDetector _interactableDetector;
    [SerializeField] HeroStatusView _statusView;

    HeroStateMachine _stateMachine;
    [SerializeField] HeroStateType _stateType;

    bool _attackInput;          // АјАн АЁДЩЧбСі ПЉКЮПЁ ДыЧб ХфХЋ(РЬАд РжОюОп АјАн ИгНХПЁ ЕПРќРЛ ГжРЛМі РжРН)


    public Mover Mover => _mover;
    public HeroAnimator Animator => _animator;
    public InteractableDetector InteractableDetector => _interactableDetector;
    public HeroStatusView StatusView => _statusView;
    public bool AttackInput => _attackInput;

    public void Initialize()
    {
        _mover.OnMoved += OnMoved;
        _interactableDetector.OnDetected += OnInteractableDetected;
        _interactableDetector.OnMissed += OnInteractableMissed;

        _stateMachine = new HeroStateMachine(this);
    }

    public void Update()
    {
        _stateMachine.UpdateState();
        _stateType = _stateMachine.CurrentState.StateType;
    }

    /// <summary>
    /// РЬЕП РдЗТРЛ ЙоОвРЛ ЖЇ MoverРЧ MoveЧдМіИІ ШЃУтЧЯПЉ
    /// ПЕПѕРЛ ПђСїРЬДТ ЧдМі
    /// </summary>
    /// <param name="direction"></param>
    public void Move(Vector3 direction)
    {
        _mover.Move(direction);
    }

    /// <summary>
    /// ПЕПѕРЧ ПђСїРгРЛ ИиУпДТ ЧдМі
    /// </summary>
    public void Stop()
    {
        _mover.Move(Vector3.zero);
    }

    /// <summary>
    /// ПЕПѕРЬ ПђСїРЯЖЇ ШЃУтЕЧДТ ЧдМі
    /// РЬЕПЧпРЛ ЖЇПЭ АќЗУЕШ ЧдМіЕщРЛ ШЃУтЧбДй.
    /// </summary>
    /// <param name="velocity"></param>
    void OnMoved(Vector3 velocity)
    {
        _animator.OnMove(velocity);
    }

    /// <summary>
    /// АјАн РдЗТРЛ ЙоОвРЛ ЖЇ ЧУЗЁБзИІ trueЗЮ РќШЏЧЯДТ ЧдМі
    /// </summary>
    public void OnAttackInput()
    {
        _attackInput = true;
    }

    /// <summary>
    /// АјАн РдЗТ ЧУЗЁБзИІ falseЗЮ РќШЏЧЯДТ ЧдМі
    /// ЛѓХТ ИгНХПЁМ­ СЖАЧРЛ ЦЧДмЧЯПЉ РЬ ЧдМіИІ ШЃУтЧи ЧУЗЁБзИІ СЖР§
    /// </summary>
    public void ClearAttackInput()
    {
        _attackInput = false;
    }

    /// <summary>
    /// IInteractableРЛ АЈСіЧпРЛ ЖЇ РкЕПРИЗЮ ШЃУтЕЧДТ ЧдМі
    /// </summary>
    /// <param name="interactable"></param>
    void OnInteractableDetected(IInteractable interactable)
    {
        _statusView.SetInetractionGuide(true, interactable.GuidePoint);
    }

    /// <summary>
    /// IInteractable АЈСіИІ НЧЦаЧпРЛ ЖЇ РкЕПРИЗЮ ШЃУтЕЧДТ ЧдМі
    /// </summary>
    void OnInteractableMissed()
    {
        _statusView.SetInetractionGuide(false, Vector3.zero);
    }

    public void OnAttackStart()
    {
        
    }

    /// <summary>
    /// ЛѓШЃРлПыРЛ МіЧрЧЯДТ ЧдМі
    /// </summary>
    public void ExecuteInteraction()
    {
        _interactableDetector.ExecuteInteraction();
        Debug.Log("ЛѓШЃРлПы НЧНУ");
    }
}
